fs = require 'fs'
{print} = require 'util'
{spawn, exec} = require 'child_process'
 
log = (message, explanation) ->
  console.log message + ' ' + (explanation or '')
 
build = (watch, callback) ->
  if typeof watch is 'function'
    callback = watch
    watch = false
  options = ['-c','-m','code.coffee']
  options.unshift '-w' if watch
 
  coffee = spawn 'coffee', options
  coffee.stdout.on 'data', (data) -> print data.toString()
  coffee.stderr.on 'data', (data) -> log data.toString()
  coffee.on 'exit', (status) -> callback?() if status is 0
 
task 'sbuild', 'generate javascript files.', ->
  build -> log "Done building."